# Generated by Django 5.2.3 on 2025-06-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conveniences",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
