# Generated by Django 5.2.3 on 2025-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
