# Generated by Django 5.2.3 on 2025-06-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_profile_is_guest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="conveniences",
        ),
    ]
