# Generated by Django 5.2.3 on 2025-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_order_conveniences"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="conveniences",
            field=models.ManyToManyField(blank=True, to="account.conveniences"),
        ),
    ]
