# Generated by Django 5.2.3 on 2025-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_order_conveniences"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="wishes",
            field=models.TextField(blank=True, null=True, verbose_name="Пожелания"),
        ),
    ]
