# Generated by Django 5.2.3 on 2025-06-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_order_wishes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="arrival_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
