# Generated by Django 5.2.3 on 2025-06-23 15:32

import account.models
import django.db.models.deletion
from django.db import migrations, models

def create_roomtypes(apps, schema_editor):
    RoomType = apps.get_model('account', 'RoomType')
    RoomType.objects.create(name='Стандарт', description='...', capacity=2)
    RoomType.objects.create(name='Люкс', description='...', capacity=3)

class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_order_arrival_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="room",
            name="conveniences",
        ),
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tariff",
            name="room",
        ),
        migrations.AddField(
            model_name="room",
            name="number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tariff",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("capacity", models.PositiveIntegerField()),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="room_types/"),
                ),
                (
                    "conveniences",
                    models.ManyToManyField(blank=True, to="account.conveniences"),
                ),
            ],
        ),
        migrations.RunPython(create_roomtypes),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="account.roomtype",
            ),
        ),
        migrations.AddField(
            model_name="tariff",
            name="room_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariffs",
                to="account.roomtype",
            ),
        ),
        migrations.CreateModel(
            name="RoomTypeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=account.models.room_type_image_upload_to
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="account.roomtype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RoomImage",
        ),
       
    ]
