# Generated by Django 5.2.3 on 2025-06-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_remove_room_capacity_remove_room_conveniences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="account.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="roomtypeimage",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="account.roomtype",
            ),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariffs",
                to="account.roomtype",
            ),
        ),
    ]
