# Generated by Django 5.2.3 on 2025-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_room_room_type_alter_roomtypeimage_room_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.PositiveIntegerField(),
        ),
    ]
