# Generated by Django 5.2.3 on 2025-06-23 15:35

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_alter_room_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("room_type", "number")},
        ),
    ]
