# Generated by Django 5.2.3 on 2025-06-23 15:35

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_room_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=set(),
        ),
    ]
