# Generated by Django 5.2.3 on 2025-06-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_alter_room_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=50, verbose_name="Электронная почта"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=20, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="second_name",
            field=models.CharField(max_length=20, verbose_name="Фамилия"),
        ),
    ]
