# Generated by Django 5.2.3 on 2025-06-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_profile_email_alter_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
