# Generated by Django 5.2.3 on 2025-06-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_profile_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="conveniences",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="CSS класс иконки или путь к изображению",
                max_length=100,
                null=True,
            ),
        ),
    ]
