# Generated by Django 5.2.3 on 2025-06-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_conveniences_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tariff",
            name="max_guests",
        ),
        migrations.AddField(
            model_name="tariff",
            name="bed_type",
            field=models.CharField(
                choices=[
                    ("double", "Двуспальная кровать"),
                    ("single_two", "Две одноместные кровати"),
                    ("queen", "Кровать queen size"),
                    ("king", "Кровать king size"),
                ],
                default="double",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="capacity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
