# Generated by Django 5.2.3 on 2025-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_remove_tariff_max_guests_tariff_bed_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачен"),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_file",
            field=models.FileField(
                blank=True, null=True, upload_to="receipts/", verbose_name="Файл чека"
            ),
        ),
    ]
