# Generated by Django 5.2.3 on 2025-06-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_order_is_paid_order_receipt_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
    ]
