# Generated by Django 4.2.14 on 2026-01-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='cancellation',
            field=models.CharField(help_text='Условия отмены', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
