# Generated by Django 4.2.14 on 2026-01-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_profile_phone_number_alter_tariff_cancellation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveniences',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='bed_type',
            field=models.CharField(choices=[('double', 'Двуспальная кровать'), ('single_two', 'Две одноместные кровати'), ('queen', 'Кровать queen size'), ('king', 'Кровать king size')], default='double', max_length=255),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='cancellation',
            field=models.CharField(help_text='Условия отмены', max_length=2000),
        ),
    ]
